//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ir.afe.www
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.afe.ir/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.afe.ir/", ConfigurationName="ir.afe.www.BoxServiceSoap")]
    public interface BoxServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.afe.www.SendMessageResponse> SendMessageAsync(ir.afe.www.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/SendBusinessCard", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.afe.www.SendBusinessCardResponse> SendBusinessCardAsync(ir.afe.www.SendBusinessCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/SendWappush", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.afe.www.SendWappushResponse> SendWappushAsync(ir.afe.www.SendWappushRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendMessageRequestBody Body;
        
        public SendMessageRequest()
        {
        }
        
        public SendMessageRequest(ir.afe.www.SendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ir.afe.www.ArrayOfString Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type;
        
        public SendMessageRequestBody()
        {
        }
        
        public SendMessageRequestBody(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string Message, string Type)
        {
            this.Username = Username;
            this.Password = Password;
            this.Number = Number;
            this.Mobile = Mobile;
            this.Message = Message;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendMessageResponseBody Body;
        
        public SendMessageResponse()
        {
        }
        
        public SendMessageResponse(ir.afe.www.SendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.afe.www.ArrayOfString SendMessageResult;
        
        public SendMessageResponseBody()
        {
        }
        
        public SendMessageResponseBody(ir.afe.www.ArrayOfString SendMessageResult)
        {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBusinessCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBusinessCard", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendBusinessCardRequestBody Body;
        
        public SendBusinessCardRequest()
        {
        }
        
        public SendBusinessCardRequest(ir.afe.www.SendBusinessCardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendBusinessCardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ir.afe.www.ArrayOfString Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Type;
        
        public SendBusinessCardRequestBody()
        {
        }
        
        public SendBusinessCardRequestBody(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string ContactName, string PhoneNumber, string Type)
        {
            this.Username = Username;
            this.Password = Password;
            this.Number = Number;
            this.Mobile = Mobile;
            this.ContactName = ContactName;
            this.PhoneNumber = PhoneNumber;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBusinessCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBusinessCardResponse", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendBusinessCardResponseBody Body;
        
        public SendBusinessCardResponse()
        {
        }
        
        public SendBusinessCardResponse(ir.afe.www.SendBusinessCardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendBusinessCardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.afe.www.ArrayOfString SendBusinessCardResult;
        
        public SendBusinessCardResponseBody()
        {
        }
        
        public SendBusinessCardResponseBody(ir.afe.www.ArrayOfString SendBusinessCardResult)
        {
            this.SendBusinessCardResult = SendBusinessCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWappushRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWappush", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendWappushRequestBody Body;
        
        public SendWappushRequest()
        {
        }
        
        public SendWappushRequest(ir.afe.www.SendWappushRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendWappushRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ir.afe.www.ArrayOfString Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Type;
        
        public SendWappushRequestBody()
        {
        }
        
        public SendWappushRequestBody(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string Url, string Description, string Type)
        {
            this.Username = Username;
            this.Password = Password;
            this.Number = Number;
            this.Mobile = Mobile;
            this.Url = Url;
            this.Description = Description;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWappushResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWappushResponse", Namespace="http://www.afe.ir/", Order=0)]
        public ir.afe.www.SendWappushResponseBody Body;
        
        public SendWappushResponse()
        {
        }
        
        public SendWappushResponse(ir.afe.www.SendWappushResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendWappushResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.afe.www.ArrayOfString SendWappushResult;
        
        public SendWappushResponseBody()
        {
        }
        
        public SendWappushResponseBody(ir.afe.www.ArrayOfString SendWappushResult)
        {
            this.SendWappushResult = SendWappushResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface BoxServiceSoapChannel : ir.afe.www.BoxServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BoxServiceSoapClient : System.ServiceModel.ClientBase<ir.afe.www.BoxServiceSoap>, ir.afe.www.BoxServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BoxServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BoxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BoxServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoxServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BoxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoxServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BoxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.afe.www.SendMessageResponse> ir.afe.www.BoxServiceSoap.SendMessageAsync(ir.afe.www.SendMessageRequest request)
        {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.afe.www.SendMessageResponse> SendMessageAsync(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string Message, string Type)
        {
            ir.afe.www.SendMessageRequest inValue = new ir.afe.www.SendMessageRequest();
            inValue.Body = new ir.afe.www.SendMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Number = Number;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            inValue.Body.Type = Type;
            return ((ir.afe.www.BoxServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.afe.www.SendBusinessCardResponse> ir.afe.www.BoxServiceSoap.SendBusinessCardAsync(ir.afe.www.SendBusinessCardRequest request)
        {
            return base.Channel.SendBusinessCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.afe.www.SendBusinessCardResponse> SendBusinessCardAsync(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string ContactName, string PhoneNumber, string Type)
        {
            ir.afe.www.SendBusinessCardRequest inValue = new ir.afe.www.SendBusinessCardRequest();
            inValue.Body = new ir.afe.www.SendBusinessCardRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Number = Number;
            inValue.Body.Mobile = Mobile;
            inValue.Body.ContactName = ContactName;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.Type = Type;
            return ((ir.afe.www.BoxServiceSoap)(this)).SendBusinessCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.afe.www.SendWappushResponse> ir.afe.www.BoxServiceSoap.SendWappushAsync(ir.afe.www.SendWappushRequest request)
        {
            return base.Channel.SendWappushAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.afe.www.SendWappushResponse> SendWappushAsync(string Username, string Password, string Number, ir.afe.www.ArrayOfString Mobile, string Url, string Description, string Type)
        {
            ir.afe.www.SendWappushRequest inValue = new ir.afe.www.SendWappushRequest();
            inValue.Body = new ir.afe.www.SendWappushRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Number = Number;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Url = Url;
            inValue.Body.Description = Description;
            inValue.Body.Type = Type;
            return ((ir.afe.www.BoxServiceSoap)(this)).SendWappushAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BoxServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BoxServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BoxServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.afe.ir/WebService/V4/BoxService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BoxServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.afe.ir/WebService/V4/BoxService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BoxServiceSoap,
            
            BoxServiceSoap12,
        }
    }
}
